services:

  discovery-server:
    image: husarnet/ros:humble-ros-core
    network_mode: service:husarnet
    ipc: service:husarnet
    depends_on: 
      husarnet: { condition: service_healthy }
    environment:
      - DDS_CONFIG=HUSARNET_DISCOVERY_SERVER
    command: fast-discovery-server -x /dds-husarnet-ds.xml

  chatter:
    build:
      context: .
      args:
        - ROS_DISTRO=${ROS_DISTRO}
    network_mode: service:husarnet
    ipc: service:husarnet
    depends_on: 
      husarnet: { condition: service_healthy }
    environment:
      - DDS_CONFIG
      - ROS_DISCOVERY_SERVER
    command: ros2 run demo_nodes_cpp ${CHATTER_ROLE}

  husarnet:
    image: husarnet/husarnet:2.0.13
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment: 
      - HOSTNAME=${CHATTER_ROLE}
      - JOINCODE
      - WAIT_HOSTNAMES
      - HUSARNET_DEBUG=1